---

sudo: required

dist: trusty

language: generic

before_install:
  - sudo apt-get install -y software-properties-common
  - sudo apt-add-repository -y ppa:fkrull/deadsnakes-python2.7
  - sudo apt-get update
  - sudo apt-get -y install python2.7
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get -y install ansible

before_script:
  - sudo apt-get -y install mlocate
  - sudo updatedb
  - locate -r 'ansible/modules/extras$' -n 1
  - cd `locate -r 'ansible/modules/extras$' -n 1`
  - ls -la $TRAVIS_BUILD_DIR/tests/gluster_volume_disperse.patch
  - patch -p1 $TRAVIS_BUILD_DIR/tests/gluster_volume_disperse.patch
  - echo $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR

script:
  - sudo ansible-playbook tests/test.yml -i tests/hosts --syntax-check
  - sudo ansible-playbook tests/test.yml -i tests/hosts
  - sudo ansible-playbook tests/test.yml -i tests/hosts | grep -q 'unreachable=0.*failed=0' && exit 0 || exit 1
